baseURL = "https://littlecorner.netlify.com"
languageCode = "en-us"
title = "Benoit Laurent's Little corner"
theme = "solar-theme-hugo"
googleAnalytics = "UA-117247677-2"
enableGitInfo = true
paginate = 30
enableRobotsTXT = true
canonifyURLs = true
pygmentsStyle = "solarized-dark"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4


[params]
  author = "Benoit Laurent"
  description = "Just a blog for stuff I wanted to share"
  copyright = [
    "&copy; 2019 Benoit Laurent"
  ]
  email         =  "laurentb81@gmail.com"


[params.social]
  twitter       = "https://twitter.com/cloudmaker81"
  linkedin      = "https://www.linkedin.com/in/benoit-laurent-442a34a1"
  github        = "http://github.com/blaurent"
  email         =  "laurentb81@gmail.com"
